#ifndef __CONTROLL_TEMPLETE_H__
#define __CONTROLL_TEMPLETE_H__

//user request define
enum {
    USER_REQ_APP_WIN_ENTRY,
    USER_REQ_OOPS_WIN_ENTRY,

    USER_REQ_COOLER_ON_OFF,
    USER_REQ_COOLER_SWITCH,

    USER_REQ_SETTING,
    USER_REQ_SAVE_CLOCK,
    USER_REQ_SAVE_ALARM1,
    USER_REQ_SAVE_ALARM2,
    USER_REQ_SAVE_ALARM3,
    USER_REQ_SAVE_ALARM4,
    USER_REQ_CLR_ALARM1,
    USER_REQ_CLR_ALARM2,
    USER_REQ_CLR_ALARM3,
    USER_REQ_CLR_ALARM4,

    USER_REQ_CURSOR_DOWN,

    USER_REQ_AM,
    USER_REQ_PM,

    USER_REQ_CLR_STALL_OR_RUN_ONCE
};

#endif
