#ifndef __EVENT_DEF_H__
#define __EVENT_DEF_H__

enum{
    EVENT_ALARM_ACHIEVE = 0,
    EVENT_COOLER_MODE_1,
    EVENT_COOLER_MODE_2,
    EVENT_COOLER_MODE_3,

    EVENT_COOLER_DISABLE,
    EVENT_COOLER_ENABLE,
    EVENT_MOTOR_WORK_PREPARE,
    EVENT_MOTOR_WORK_COMPLETE,
    
    EVENT_MOTOR_TASK_RESET_AND_RUN_ONCE,

    EVENT_CLOCK_MIN_UPDATE,
    EVENT_ALARM_SORT_REFLESH,
};

#endif
